language: node_js
node_js:
- '6'
deploy:
  provider: npm
  email: alex@alexnorton.com
  skip_cleanup: true
  api_key:
    secure: fUZ13oVLfJMDILyOqfOu2qo9XiEuGMXvVFRvaH58S0wDq2LjaXPKtsDEI4tOT3hPRmkcP2lFxB8R/+HRuNst/PjouOETNuuwpuiqbhbYpPvzqqraSGvg4SU2JNLFSjafIX3WhDkCx9I8Zb0nwPlKAEP2Hn8GhoO29WtuTdekf2ZquyojJQTvzvNThey3SoBEj/UxqYn39KdolCnsKxhC/6IVhKFOdcB/afSia4YUssT1zlQ9lLhlVUwZDtusn4KVisEJr4Q4iuQrWeBkIpVXAknhssGG+TdNiaJjkOZ/ipaIQePyRY5bekPs5YIgGayelERzZ7UOQxN7PqbCYEOOZ6hRcGu/Ok3jInut/vM+QxZFTSoHgDyPR2oYKH6j2UDZrlX1kjRVz/6Q1Ncbh6sjZyhdpJdrtswnjFYr/Pj88yI1fa7KbIvONKgDlAtztp6ZtQQCnoIyoLc2qFh5be2TC9LCj/kYOmXbeOG9phNgUPJ8TuqsNW9KIb/NH2msf2Ghq76L10hiOY9bxW1sdh0gAG3xXKalq1QkSn2yK6jphc6/KCtb8HS7lb9juJrqVGmO1PIOl+l7yB3tuuikMHC6nZqeBCYrm2PNbDT5q4XBfBzdIgfJOKpkXXzuPkM0r8QeHVYPYK9HmGkbeaJIeYd0F6HDivfqONC4m12Wlh9lPCo=
  on:
    tags: true
    repo: bbc/transcript-model
